# Generated by Django 4.2.25 on 2025-11-20 17:57

import api.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=128)),
                ('status', models.CharField(default='PENDING', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=64, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='failed', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TrainAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=32)),
                ('journey_date', models.DateField()),
                ('class_type', models.CharField(default='SL', max_length=10)),
                ('quota', models.CharField(default='GN', max_length=20)),
                ('available_seats', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('train_number', 'journey_date', 'class_type', 'quota')},
            },
        ),
        migrations.CreateModel(
            name='SelectedTrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_trains', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PendingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train', models.JSONField(default=dict)),
                ('passengers', models.JSONField(default=list)),
                ('total_fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_booking', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PassengerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengers', models.JSONField(default=list)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_sessions', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BookingBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(blank=True, max_length=64, null=True)),
                ('behavior', models.JSONField()),
                ('device', models.JSONField()),
                ('human_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.CharField(default=api.models.gen_id, max_length=40, primary_key=True, serialize=False)),
                ('pnr', models.CharField(max_length=64, unique=True)),
                ('train', models.JSONField()),
                ('passengers', models.JSONField()),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('journey_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='CONFIRMED', max_length=32)),
                ('payment_status', models.CharField(default='PENDING', max_length=32)),
                ('transaction_id', models.CharField(blank=True, max_length=128, null=True)),
                ('travel_class', models.CharField(default='SL', max_length=10)),
                ('quota', models.CharField(default='GN', max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.userprofile')),
            ],
        ),
    ]
