# Generated by Django 5.0.6 on 2026-03-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_emailotp_remove_booking_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainavailability",
            name="rac_available",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="trainavailability",
            name="waiting_available",
            field=models.IntegerField(default=20),
        ),
    ]
