# Generated by Django 5.0.6 on 2026-03-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_trainavailability_rac_available_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailotp",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
