# Generated by Django 5.2.7 on 2026-03-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_emailotp_created_at"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="loginattempt",
            index=models.Index(
                fields=["timestamp"], name="api_loginat_timesta_0454b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginattempt",
            index=models.Index(
                fields=["ip_address", "timestamp"],
                name="api_loginat_ip_addr_af145a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="loginattempt",
            index=models.Index(
                fields=["username", "timestamp"], name="api_loginat_usernam_3ac809_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginattempt",
            index=models.Index(
                fields=["email", "timestamp"], name="api_loginat_email_eab493_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginattempt",
            index=models.Index(
                fields=["status", "timestamp"], name="api_loginat_status_998d48_idx"
            ),
        ),
    ]
